INSERT INTO pilotes (nom, pays)
VALUES
('Antonio Fuoco', 'Italie'),
('Miguel Molina', 'Espagne'),
('Nicklas Nielsen', 'Danemark'),
('Alessandro Pier Guidi', 'Italie'),
('James Calado', 'Royaume-Uni'),
('Antonio Giovinazzi', 'Italie'),
('Robert Kubica', 'Pologne'),
('Robert Shwartzman', 'Russie'),
('Ye Yifei', 'Chine'),
('José María López', 'Argentine'),
('Kamui Kobayashi', 'Japon'),
('Nyck de Vries', 'Pays-Bas'),
('Sébastien Buemi', 'Suisse'),
('Brendon Hartley', 'Nouvelle-Zélande'),
('Ryō Hirakawa', 'Japon'),
('Mathieu Jaminet', 'France'),
('Felipe Nasr', 'Brésil'),
('Nick Tandy', 'Royaume-Uni'),
('Michael Christensen', 'Danemark'),
('Matt Campbell', 'Australie'),
('Frédéric Makowiecki', 'France'),
('Kévin Estre', 'France'),
('André Lotterer', 'Allemagne'),
('Laurens Vanthoor', 'Belgique'),
('Earl Bamber', 'Nouvelle-Zélande'),
('Alex Lynn', 'Royaume-Uni'),
('Álex Palou', 'Espagne'),
('Sébastien Bourdais', 'France'),
('Renger van der Zande', 'Pays-Bas'),
('Scott Dixon', 'Nouvelle-Zélande'),
('Felipe Drugovich', 'Brésil'),
('Jack Aitken', 'Royaume-Uni'),
('Pipo Derani', 'Brésil'),
('Jean-Éric Vergne', 'France'),
('Mikkel Jensen', 'Danemark'),
('Nico Müller', 'Suisse'),
('Paul di Resta', 'Royaume-Uni'),
('Loïc Duval', 'France'),
('Stoffel Vandoorne', 'Belgique'),
('Raffaele Marciello', 'Suisse'),
('Dries Vanthoor', 'Belgique'),
('Marco Wittmann', 'Allemagne'),
('Robin Frijns', 'Pays-Bas'),
('René Rast', 'Allemagne'),
('Sheldon van der Linde', 'Afrique du Sud'),
('Paul-Loup Chatin', 'France'),
('Ferdinand Habsburg', 'Autriche'),
('Charles Milesi', 'France'),
('Nicolas Lapierre', 'France'),
('Mick Schumacher', 'Allemagne'),
('Matthieu Vaxiviere', 'France'),
('Matteo Cairoli', 'Italie'),
('Andrea Caldarelli', 'Italie'),
('Romain Grosjean', 'France'),
('Mirko Bortolotti', 'Italie'),
('Daniil Kvyat', 'Russie'),
('Edoardo Mortara', 'Suisse'),
('Will Stevens', 'Royaume-Uni'),
('Callum Ilott', 'Royaume-Uni'),
('Norman Nato', 'France'),
('Jenson Button', 'Royaume-Uni'),
('Phil Hanson', 'Royaume-Uni'),
('Oliver Rasmussen', 'Danemark'),
('Julien Andlauer', 'France'),
('Neel Jani', 'Suisse'),
('Harry Tincknell', 'Royaume-Uni'),
('Carl Bennett', 'États-Unis'),
('Antonio Serravalle', 'Canada'),
('Jean-Karl Vernay', 'France');
