
INSERT INTO pilotes (nom, pays)
VALUES ('Antonio Fuoco','Italie'),
('Miguel Molina','Espagne'),
('Nicklas Nielsen','Danemark'),
('Alessandro Pier Guidi','Italie'),
('James Calado','Royaume-Uni'),
('Antonio Giovinazzi','Italie'),
('Kévin Estre','France'),
('André Lotterer','Allemagne'),
('Laurens Vanthoor','Belgique'),
('Mathieu Jaminet','France'),
('Felipe Nasr','Brésil'),
('Nick Tandy','Royaume-Uni'),
('Earl Bamber','Nouvelle-Zélande'),
('Alex Lynn','Royaume-Uni'),
('Alex Palou','Espagne'),
('Sébastien Bourdais','France'),
('Renger van der Zande','Pays-Bas'),
('Scott Dixon','Nouvelle-Zélande'),
('Luis Felipe Derani','Brésil'),
('Jack Aitken','Royaume-Uni'),
('Felipe Drugovich','Brésil'),
('Jean-Éric Vergne','France'),
('Mikkel Jensen','Danemark'),
('Nico Müller','Suisse'),
('Stoffel Vandoorne','Belgique'),
('Paul Di Resta','Royaume-Uni'),
('Loïc Duval','France'),
('Paul-Loup Chatin','France'),
('Ferdinand Habsburg','Autriche'),
('Charles Milesi','France'),
('Nicolas Lapierre','France'),
('Matthieu Vaxiviere','France'),
('Mick Schumacher','Allemagne'),
('Romain Grosjean','France'),
('Andrea Caldarelli','Italie'),
('Matteo Cairoli','Italie'),
('Sheldon van der Linde','Afrique du Sud'),
('Robin Frijns','Pays-Bas'),
('René Rast','Allemagne'),
('Oliver Rasmussen','Danemark'),
('Jenson Button','Royaume-Uni'),
('Phil Hanson','Royaume-Uni');
